CREATE TABLE "houses" (
	"id" serial PRIMARY KEY NOT NULL,
	"url" text,
	"price_in_rp" double precision,
	"title" text,
	"address" text,
	"district" varchar(100),
	"city" varchar(100),
	"lat" double precision,
	"long" double precision,
	"facilities" text,
	"property_type" varchar(50),
	"ads_id" varchar(100),
	"bedrooms" integer,
	"bathrooms" integer,
	"land_size_m2" integer,
	"building_size_m2" integer,
	"carports" integer,
	"certificate" varchar(100),
	"electricity" varchar(50),
	"maid_bedrooms" integer,
	"maid_bathrooms" integer,
	"floors" integer,
	"building_age" integer,
	"year_built" integer,
	"property_condition" varchar(100),
	"building_orientation" varchar(100),
	"garages" integer,
	"furnishing" varchar(100)
);
